---
- name: Configure host settings
  tags: host
  hosts: xcp_hosts
  become: true
  vars_files:
    - vars/basics.yml
  pre_tasks:
    - name: Include tasks to gather XCP-ng facts
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/xcpfacts.yml
      when: xcp_host_uuid is undefined

    # https://serverfault.com/questions/959026/how-do-i-generate-and-set-the-locale-using-ansible
    - name: Get existing locale and language
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
      ansible.builtin.command: localectl status
      register: locale_status
      changed_when: false

    - name: Parse LANG from localectl output
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        locale_lang: "{{ locale_status.stdout |
          regex_search('LANG=([^\n]+)','\\1') |
          first }}"

    - name: Parse LANGUAGE from localectl output
      ansible.builtin.set_fact:
        locale_language: "{{ locale_status.stdout |
          regex_search('LANGUAGE=([^\n]+)','\\1') |
          default([locale_lang], true) | first }}"
  tasks:
    # https://docs.xenserver.com/en-us/citrix-hypervisor/networking/manage.html#hostname
    - name: Set host name to "xcp?"
      ansible.builtin.command:
        argv:
          - xe
          - host-set-hostname-live
          - host-uuid={{ xcp_host_uuid }}
          - host-name={{ inventory_hostname }}
      when: >-
        xcp_host_name_xe != inventory_hostname or
        xcp_host_name_os != inventory_hostname
      changed_when: true

    - name: Set time zone to "{{ system_time_zone }}"
      # https://docs.ansible.com/ansible/latest/collections/community/general/timezone_module.html
      community.general.timezone:
        name: "{{ system_time_zone }}"

    - name: Set locale to "{{ system_locale }}"
        and language to "{{ system_language }}"
      ansible.builtin.command: >-
        localectl set-locale LANG={{ system_locale }}
                         LANGUAGE={{ system_language }}
      when: >-
        locale_lang     != system_locale or
        locale_language != system_language
      changed_when: true

    - name: Enable emergency mode auto-continue
      vars:
        service_dir: /etc/systemd/system/emergency.service.d
        timeout_sec: 30
      block:
        - name: Create "{{ service_dir | basename }}/"
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
          ansible.builtin.file:
            path: "{{ service_dir }}"
            state: directory
            mode: "0755"

        - name: Create "override.conf" file
          # https://docs.ansible.com/ansible/latest/collections/community/general/ini_file_module.html
          community.general.ini_file:
            path: "{{ service_dir }}/override.conf"
            section: Service
            # item.values (in dot-notation) causes this to be written instead:
            # ExecStart=<built-in method values of dict object at 0x110a0c140>
            option: "{{ item['option'] }}"
            values: "{{ item['values'] }}"
            no_extra_spaces: true
            state: present
            mode: "0644"
          loop:
            - option: ExecStart
              values:
                - " # Clear existing entries"
                - >-
                  /usr/bin/sh -c "echo
                  'Entering emergency mode. Press Ctrl+C to cancel auto-continue.';
                  sleep {{ timeout_sec }}"
            - option: TimeoutStartSec
              values:
                - "{{ timeout_sec }}"
          loop_control:
            label: "{{ item.option }}"
          notify: Reload systemd config files

    # https://bobcares.com/blog/xcp-ng-gpu-passthrough
    # https://xcp-ng.org/forum/topic/6211/intel-gpu-passthrough-question/12
    # https://xcp-ng.org/forum/topic/3534/pci-passthrough-back-to-dom0
    # NOTE: this task updates grub.cfg, and will require system reboot
    - name: Enable GPU passthrough to VMs
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        shopt -s globstar
          set -o pipefail

        dev=($(lspci -nn | grep VGA))
        [ "$dev" ] || {
          echo "No VGA device found!"
          exit 9 # no change
        }
        echo "Found VGA device:"
        echo "${dev[*]}"

        # use globstar to find grub.cfg since
        # it could be in different locations:
        #   /boot/efi/EFI/xenserver/grub.cfg
        #   /boot/grub/grub.cfg
        grub=(/boot/**/grub.cfg)

        regex="xen-pciback\.hide=(.*0000:${dev//./\\.}.*)"
        grep -Eq "$regex" $grub && {
          echo "Already hidden."
          exit 9 # no change
        }

        echo "Hiding from dom0:"
        /opt/xensource/libexec/xen-cmdline \
          --set-dom0 "xen-pciback.hide=(0000:$dev)"
        echo "Confirm grub.cfg:"
        grep -E "$regex" $grub
      args:
        executable: /bin/bash
      register: xen_cmd
      changed_when: xen_cmd.rc == 0
      failed_when: xen_cmd.rc not in [0,9]
  handlers:
    - name: Reload systemd config files
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html
      ansible.builtin.systemd_service:
        daemon_reload: true

- name: Configure network settings
  tags: network
  hosts: xcp_hosts
  become: true
  vars_files:
    - vars/basics.yml
  tasks:
    # https://docs.xenserver.com/en-us/citrix-hypervisor/networking/manage.html#dns-servers
    - name: Set DNS name servers
      ansible.builtin.command:
        argv:
          - xe
          - pif-reconfigure-ip
          - uuid={{ xcp_pif_uuid }}
          - mode=static
          - IP={{ ansible_host }}
          - netmask=255.255.255.0
          - gateway={{ name_servers[0] }}
          - DNS={{ name_servers | join(',') }}
      when: xcp_name_servers != name_servers
      register: result
      # it's normal to lose connection
      failed_when: result.rc != 0 and
        'Lost connection to the server' not in result.stderr
      changed_when: true

    # https://docs.xcp-ng.org/networking/#-dns-search-domains
    - name: Set DNS search domains
      ansible.builtin.command:
        argv:
          - xe
          - pif-param-set
          - uuid={{ xcp_pif_uuid }}
          - other-config:domain={{ search_domains | join(',') }}
      when: xcp_search_domains != search_domains
      changed_when: true

- name: Suppress default MOTD message
  tags: motd
  hosts: xcp_hosts
  vars:
    motd_file: /etc/motd
    motd_xs_file: "{{ motd_file }}.xs"
    motd_xs_bak: "{{ motd_xs_file }}.bak"
  pre_tasks:
    - name: Check if MOTD backup exists?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html
      ansible.builtin.stat:
        path: "{{ motd_xs_bak }}"
      register: motd_backup
  tasks:
    - name: Backup original motd.xs file
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
      ansible.builtin.copy:
        src: "{{ motd_xs_file }}"
        dest: "{{ motd_xs_bak }}"
        remote_src: true
        mode: preserve
      when: not motd_backup.stat.exists

    - name: Truncate original motd file
      ansible.builtin.copy:
        content: ""
        dest: "{{ item }}"
        mode: "0644"
      loop:
        - "{{ motd_file    }}"
        - "{{ motd_xs_file }}"

- name: Update XAPI certificates
  tags: certs
  hosts: xcp_hosts
  vars:
    xapi_pem_file: /etc/xensource/xapi-ssl.pem
    xapi_pem_bak: "{{ xapi_pem_file }}.bak"
  pre_tasks:
    - name: Check if PEM backups exist?
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - "{{ xapi_pem_bak  }}" # the actual backup check
        - "{{ xapi_pem_file }}" # get file mode and group
      loop_control:
        label: "{{ item | basename }}"
      register: pem_backups

    - name: Fetch certificates from PKI
      run_once: true
      block:
        - name: Fetch cert files from PKI
          delegate_to: "{{ pki_host }}"
          ansible.builtin.command: cat certs/{{ item }}
          loop:
            - xcp.key
            - xcp.pem # contains intermediate & root CA certs
          register: cert_files
          changed_when: false

        - name: Set xapi_pem_data fact
          # IMPORTANT: facts are not stored in ansible_facts
          # on localhost--they're simply top-level variables
          delegate_to: localhost
          vars:
            # for some reason using '\n' inside Jinja2
            # expressions produces literal backslash-n
            newline: "{{ '\n' }}"
          ansible.builtin.set_fact:
            # XCP-ng expects xapi-ssl.pem to contain
            # both private key and certificate chain
            # (original has empty line between them)
            xapi_pem_data: |-
              {{ cert_files.results[0].stdout | trim ~ newline }}
              {{ cert_files.results[1].stdout | trim ~ newline }}
  tasks:
    - name: Backup existing certificates
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ item }}.bak"
        remote_src: true
        mode: preserve
      loop:
        # make sure order is same
        # as pem_backups.results!
        - "{{ xapi_pem_file }}"
      loop_control:
        label: "{{ item | basename }}"
        index_var: i
      when: not pem_backups.results[i*2].stat.exists

    - name: Update XAPI certificates
      vars:
        stat: "{{ pem_backups.results[1].stat }}"
      ansible.builtin.copy:
        content: "{{ xapi_pem_data }}"
        dest: "{{ xapi_pem_file }}"
        group: "{{ stat.gid }}"
        mode: "{{ stat.mode }}"
      loop:
        - "{{ xapi_pem_file }}"
      loop_control:
        label: "{{ item | basename }}"
      notify: Restart XAPI service
  handlers:
    - name: Restart XAPI service
      ansible.builtin.systemd_service:
        name: xapi
        state: restarted
