---
- name: Debug parsing size with units
  hosts: localhost
  tasks:
    - name: Parse memory size with units
      vars:
        memory: "0"
        # human_to_bytes does not understand IEC units like GiB
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/human_to_bytes_filter.html
        bytes1: "{{ memory | ansible.builtin.human_to_bytes }}"
        # convert_to_bytes does not understand SI units like GB
        # https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/convert_to_bytes_filter.html
        bytes2: "{{ memory | ovirt.ovirt.convert_to_bytes }}"
      ansible.builtin.debug:
        msg: bytes1={{ bytes1 }} bytes2={{ bytes2 }}

- name: Test AWX workflow behaviors
  tags: awx
  hosts: localhost
  tasks:
    # PLAYBOOKS is passed in by play.sh when
    # running from CLI, and by awx.setup.yml
    # when running our AWX project workflows
    - name: Show PLAYBOOKS var
      ansible.builtin.debug:
        var: PLAYBOOKS | default(none)

    - name: Show run/skip tags
      vars:
        tagging:
          # ansible_run_tags is a `frozenset` in Python,
          # so must coerce to list to compare to a list
          all_tags: "{{ ansible_run_tags | list == ['all'] }}"
          # ansible_run_tags == ['all'] if NO tags were provided
          run_tags: "{{ ansible_run_tags }}"
          # ansible_skip_tags == [] if NO skip tags were provided
          skip_tags: "{{ ansible_skip_tags }}"
      ansible.builtin.debug:
        var: tagging
