---
- name: Include Python 3 installation playbook
  ansible.builtin.import_playbook: python3.yml
  tags: python3

- name: Include packages installation playbook
  ansible.builtin.import_playbook: packages.yml
  tags: packages

- name: Include host & network settings playbook
  ansible.builtin.import_playbook: basics.yml
  tags: basics

- name: Include home directory setup playbook
  ansible.builtin.import_playbook: files.yml
  tags: files

- name: Include VM configurations playbook
  ansible.builtin.import_playbook: vms.yml
  tags: vms
