---
- name: Configure VM settings
  hosts: xcp1
  gather_facts: false
  vars_files:
    - vars/vms.yml
  tasks:
    # https://docs.xcp-ng.org/guides/autostart-vm
    - name: Enable auto-starting VMs
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        # run Bash to load .bashrc in order to
        # use exported functions and variables
        exec /bin/bash -l <<'EOT'
        set -o pipefail

        HOSTS=({{ auto_start_vms | join(' ') }})
        rc=9 # no change

        for vm in "${HOSTS[@]}"; do
          uuid_var="UUID_${vm^^}"

          uuid="${!uuid_var}"
          [ "${uuid}" ] || {
            echo >&2 "Unknown VM: $vm"
            exit 1
          }
          xe vm-param-get uuid="$uuid" \
             param-name=other-config | \
            grep -q "auto_poweron: true" || {

            xe vm-param-set uuid="$uuid" \
               other-config:auto_poweron=true || \
              exit $?
            rc=0
          }
        done
        exit $rc
        EOT
      register: param_set
      changed_when: param_set.rc == 0
      failed_when: >-
        param_set.rc != 0 and
        param_set.rc != 9
  any_errors_fatal: true
