# xcpng_root_pass: {vault.yml}
#  xoa_admin_pass: {vault.yml}

pki_host: "{{ groups['pki_any'] | first }}"

ansible_user: root
# no longer setting SSH key file here so that AWX can inject it
# by credentials while play.sh exports ANSIBLE_PRIVATE_KEY_FILE
# ansible_ssh_private_key_file: >-
#   {{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/{{
#      lookup('ansible.builtin.env', 'USER') }}.pem
ansible_ssh_password: "{{ xcpng_root_pass }}"
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o ConnectTimeout=5
  -o LogLevel=error

ansible_python_interpreter: /usr/bin/python3

# localhost fact `project_dir` is set by top-level playbook "main.yml"
project_dir: "{{ hostvars['localhost']['project_dir'] |
  default(playbook_dir | ansible.builtin.dirname) }}"
vars_dir: "{{ project_dir }}/vars"
tasks_dir: "{{ project_dir }}/tasks"
templates_dir: "{{ project_dir }}/templates"
files_dir: "{{ project_dir }}/files"
scripts_dir: "{{ project_dir }}/scripts"

homelab_domain: fourteeners.local
search_domains:
  - "{{ homelab_domain }}"
